version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: okok
      POSTGRES_PASSWORD: okok
      POSTGRES_DB: okok
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
    pg-data:
